-- Live compliance: obligations (rule library) + per-tenant status
\connect cyberwatch
CREATE TABLE IF NOT EXISTS grc.obligations (
  id text PRIMARY KEY, framework text, clause text, requirement text, applicability text, cadence text,
  control text, module text, evidence_expected text, phase text, auto_key text, sort int
);
CREATE TABLE IF NOT EXISTS grc.compliance_status (
  tenant_id uuid NOT NULL,
  obligation_id text NOT NULL REFERENCES grc.obligations(id),
  status text NOT NULL DEFAULT 'Not Assessed',
  owner text, notes text,
  evidence_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_by text, updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, obligation_id)
);
INSERT INTO grc.obligations(id,framework,clause,requirement,applicability,cadence,control,module,evidence_expected,phase,auto_key,sort) VALUES
('RBI-01','RBI','Sec 6','IT Strategy Committee of the Board (min 3 directors; IT-expert independent chair)','Banks; NBFC Top/Upper/Middle; CIC; AIFI','Quarterly','Governance module tracks committee cadence, membership & minutes','M4','Committee minutes / board pack','P2',NULL,0),
('RBI-02','RBI','Sec 7','Senior management IT Steering Committee','As above','Quarterly','Same governance cadence tracking','M4','Committee minutes','P2',NULL,1),
('RBI-03','RBI','Sec 9','IT services mgmt; asset CIA classification; EOS/AMC tracking','As above','Continuous','Asset inventory with CIA classification & end-of-life tracking','M1','Asset register','MVP','asset_inventory',2),
('RBI-04','RBI','Sec 10','Third-party arrangements; vendor & supply-chain risk','As above','Ongoing / annual','Vendor risk assessments, concentration & right-to-audit','M5','Vendor assessment','P3',NULL,3),
('RBI-05','RBI','Sec 12(f)','Source-code escrow for critical applications','As above','Per project','Source-code escrow tracking','M2','Escrow record','P2',NULL,4),
('RBI-06','RBI','Sec 12(g)','Vendor certificate: app free of known vulnerabilities / malware / covert channels','As above','Per release / change','Vendor attestation capture & refresh workflow','M2','Vendor attestation','P2',NULL,5),
('RBI-07','RBI','Sec 12(h)','New IT products: product approval & quality assurance','As above','Per product','Product-approval & QA workflow','M4','Approval record','P2',NULL,6),
('RBI-08','RBI','Sec 13','Change and patch management','As above','Continuous','Patch/change tracking tied to remediation SLAs','M1','Patch / change record','MVP','remediation_sla',7),
('RBI-09','RBI','Sec 15','Audit trails / logging on critical & sensitive apps','As above','Continuous','Append-only, tamper-evident audit log','Platform','Audit log export','MVP','audit_trail',8),
('RBI-10','RBI','Sec 16','Cryptographic controls (strong, non-deprecated algorithms)','As above','Continuous','Crypto inventory + KMS-managed keys (India-resident)','Platform','Crypto inventory','P2',NULL,9),
('RBI-11','RBI','Sec 19','Access controls; MFA for privileged users','As above','Continuous','RBAC + enforced MFA; periodic access review','Platform','Access review','MVP',NULL,10),
('RBI-12','RBI','Sec 21','Define RPO/RTO for critical systems; IT maturity metrics','As above','Annual review','DR configuration records RPO/RTO per critical system','M3','DR policy evidence','P3',NULL,11),
('RBI-13','RBI','Sec 24','Information Security & Cyber Security Policy; CCMP; Information Security Committee','As above','Annual review','Policy management with versioned board-approved policies','M4','Policy documents','P2',NULL,12),
('RBI-14','RBI','Sec 24(d)(4)','CISO''s office shall manage & monitor the Security Operations Centre (SOC)','As above','Continuous','SOC module / SOC-efficacy reporting','M3','SOC efficacy report','P3',NULL,13),
('RBI-15','RBI','Sec 25','Annual risk assessment; anti-phishing measures','As above','Annual','Risk-assessment workflow & register','M4','Risk assessment','P2',NULL,14),
('RBI-16','RBI','Sec 26','VA at least every 6 months & PT at least every 12 months for critical / DMZ customer-facing systems; CVSS scoring; time-bound remediation','As above','VA 6-monthly / PT 12-monthly','VAPT orchestration cadence engine auto-schedules per asset criticality','M1','VAPT report','MVP','vapt_conducted',15),
('RBI-17','RBI','Sec 26','VA/PT across lifecycle & after major change; PT preferably on production; independent trained experts','As above','Per change / lifecycle','Release-triggered scans + auditor-independence tracking','M1','Scan record','MVP',NULL,16),
('RBI-18','RBI','Sec 27','Cyber incident response & recovery; forensic/RCA; proactive reporting to CERT-In & RBI','As above','Per incident','Incident workflow with regulator-notification templates','M3','Incident report','P3',NULL,17),
('RBI-19','RBI','Sec 29','DR drills at least half-yearly for critical systems; meet RTO/RPO','As above','Half-yearly','DR-drill scheduling & evidence capture','M3','DR drill evidence','P3',NULL,18),
('RBI-20','RBI','Sec 30','IS Audit — ACB-approved policy reviewed annually; risk-based; continuous auditing of critical systems','As above','Annual','IS-audit workpaper generation & evidence','M6','IS-audit workpapers','P2',NULL,19),
('RBI-21','RBI','Annex 1','Baseline cyber-security & resilience controls; Cyber Crisis Management Plan','Scheduled commercial banks','Ongoing','Baseline control library mapped to evidence','M7','Control evidence','P2',NULL,20),
('RBI-22','RBI','Levels I-IV','Graded controls; VA/PT from Level II; C-SOC from Level III','Urban co-operative banks','Graded / annual','Graded control profiles by UCB level','M7','Self-assessment','P3',NULL,21),
('RBI-23','RBI','-','Vendor due diligence, right-to-audit, security over outsourced IT','REs (excl. Base-Layer NBFC)','Ongoing','Vendor risk module with right-to-audit tracking','M5','Vendor contract clauses','P3',NULL,22),
('RBI-24','RBI','-','Secure SDLC & application-level controls for payment apps','Banks / card-issuers / PSOs','Continuous','AppSec secure-SDLC gates for payment apps','M2','SDLC evidence','P2',NULL,23),
('RBI-25','RBI','Dir. 70B','Report specified cyber incidents within 6 hours of notice','All (statutory)','Within 6 hours','CERT-In reporting workflow with 6-hour SLA clock','M3','CERT-In acknowledgement','P3',NULL,24),
('SEBI-01','SEBI','GV.RR','Governance — roles, responsibilities & authorities (Board / CISO)','All REs (graded)','Ongoing','Governance roles & responsibility matrix','M4','Governance records','P2',NULL,25),
('SEBI-02','SEBI','GV.PO (S1)','Cyber policy; VAPT required after every major release of applications/software','All REs','Per major release','CI/CD release-triggered VAPT','M1','Scan on release','MVP',NULL,26),
('SEBI-03','SEBI','GV.OV.S4','Cyber Capability Index (CCI) — 23 weighted parameters','MIIs (half-yearly, 3rd-party); Qualified REs (yearly, self)','Half-yearly / yearly','CCI computation engine','M4','CCI report','P2',NULL,27),
('SEBI-04','SEBI','GV.OV','Automated compliance dashboard (log-aggregator integrated)','MIIs & Qualified REs','Continuous','Automated compliance dashboard','M4','Dashboard export','P2',NULL,28),
('SEBI-05','SEBI','GV.SC.S5','SBOM for all software in core & critical operations (supplier, components, transitive deps, licences, hashes)','All REs','Ongoing / per release','SBOM generation & management (CycloneDX)','M2','SBOM artefact','P2',NULL,29),
('SEBI-06','SEBI','GV.SC','Supply-chain risk management (third-party software & services)','All REs','Ongoing','Vendor / supply-chain risk module','M5','Vendor assessment','P3',NULL,30),
('SEBI-07','SEBI','ID.AM','Asset management — hardware/software/data inventory & classification','All REs','Continuous','Asset inventory with classification','M1','Asset register','MVP','asset_inventory',31),
('SEBI-08','SEBI','ID.RA','Risk assessment','All REs','Periodic','Risk-assessment workflow','M4','Risk assessment','P2',NULL,32),
('SEBI-09','SEBI','PR.AA','Identity, authentication & access control; MFA; privileged access','All REs','Continuous','RBAC + MFA; privileged-access controls','Platform','Access review','MVP',NULL,33),
('SEBI-10','SEBI','PR.DS','Data security & classification; encryption; DLP','All REs','Continuous','Encryption/KMS + data classification','Platform','Encryption evidence','P2',NULL,34),
('SEBI-11','SEBI','PR.AS','Application security & secure SDLC (SAST/DAST); links to SBOM','All REs','Per release','AppSec orchestration (SAST/DAST/SCA), CERT-In empanelled','M2','Scan report','P2',NULL,35),
('SEBI-12','SEBI','PR.MA (S3)','Patch / maintenance; virtual patching permitted as compensating control','All REs','High-sev patch: 1 week','Remediation SLA engine + virtual-patch capture','M1','Remediation record','MVP',NULL,36),
('SEBI-13','SEBI','PR.NS','Network security & segmentation','All REs','Continuous','Network segmentation (deployment architecture)','Platform','Network diagram / config','P3',NULL,37),
('SEBI-14','SEBI','PR.CS','Cloud security (MeitY-empanelled + STQC; periodic cloud VAPT)','REs using cloud','Ongoing','Cloud asset VAPT & config assessment','M1','Cloud VAPT report','P3',NULL,38),
('SEBI-15','SEBI','DE.CM','Continuous monitoring / SOC; Market-SOC (NSE/BSE) for small & self-cert REs','All REs; small→M-SOC','Continuous','SOC / M-SOC onboarding & monitoring','M3','SOC logs / efficacy','P3',NULL,39),
('SEBI-16','SEBI','DE.VA','VAPT (manual exploitation) by CERT-In empanelled org; cyber audit','MIIs/QSBs half-yearly; other REs annual','Annual / half-yearly','VAPT orchestration + managed CERT-In-empanelled testing','M1','VAPT report','MVP','vapt_conducted',40),
('SEBI-17','SEBI','DE.VA','Quarterly vulnerability scans','As applicable by category','Quarterly','Scheduled vulnerability scans','M1','Scan record','MVP','vapt_conducted',41),
('SEBI-18','SEBI','GV.OV / Audit','Cyber audit twice a year + ISO 27001 certification evidence','MIIs & Qualified REs','Half-yearly','Audit workpapers + certification tracking','M6','Audit report','P2',NULL,42),
('SEBI-19','SEBI','RS.CO','Incident reporting to SEBI & CERT-In','All REs','Within 6 hours','Incident workflow + SEBI/CERT-In templates','M3','Incident report','P3','incident_reporting',43),
('SEBI-20','SEBI','RS.AN','Incident analysis & forensics; high/critical → mandatory forensic audit','All REs','Per incident','Forensic-audit trigger for high/critical incidents','M3','Forensic report','P3',NULL,44),
('SEBI-21','SEBI','RC.RP','Recovery — declare disaster within 30 min; RTO 2 h; RPO 15 min (critical)','All REs (critical systems)','Targets','DR configuration + evidence aligned to targets','M3','DR evidence','P3',NULL,45),
('SEBI-22','SEBI','PR.MA / DE.VA','Close high-severity patch findings in 1 week; other VAPT findings within 3 months of report','All REs','SLA on finding','Remediation SLA engine with graded due dates','M1','Closure evidence','MVP','remediation_sla',46),
('SEBI-23','SEBI','PR.DS / DATALOC','Encryption keys & key-management within India (BYOK)','All REs','Ongoing','India-resident KMS / BYOK','Platform','Residency attestation','MVP',NULL,47),
('SEBI-24','SEBI','CLASSIFY','RE classification each financial year drives graded obligations','All REs','Annual (per FY)','Tenant re_category drives cadence & applicability','M7','Classification record','MVP',NULL,48),
('SEBI-25','SEBI','CERTIF','ISO 27001 certification (with audit scope: PDC, DR, NDR, SOC, colocation)','MIIs & Qualified REs','Ongoing','Certification tracking & scope evidence','M4','ISO 27001 certificate','P2',NULL,49),
('SEBI-26','SEBI','CYBER-INS','Cyber insurance (as applicable)','As applicable','Ongoing','Insurance-policy record tracking','M4','Policy record','P4',NULL,50)
ON CONFLICT (id) DO UPDATE SET framework=EXCLUDED.framework, clause=EXCLUDED.clause, requirement=EXCLUDED.requirement,
  applicability=EXCLUDED.applicability, cadence=EXCLUDED.cadence, control=EXCLUDED.control, module=EXCLUDED.module,
  evidence_expected=EXCLUDED.evidence_expected, phase=EXCLUDED.phase, auto_key=EXCLUDED.auto_key, sort=EXCLUDED.sort;
